# version: "3.9"

services:
  app:
    build: .
    container_name: email-gateway
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
     
      - DATABASE_URL=postgres://postgres:newpassword@postgres:5432/email_gateway
    
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # For local development with hot reload, uncomment:
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # command: npm run start:dev

  db:
    image: postgres:16-alpine
    container_name: email-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123#
      - POSTGRES_DB=email_gateway
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: email-redis

volumes:
  pg_data:
